Removed non-ASCII characters in comments.
These characters caused the `macro2m4.py` script to terminate with an error:

    $ make maintainer-all
    ...
    python ./macro2m4.py "m4/ax_compiler_flags_cflags.m4" "stage/ax_compiler_flags_cflags.m4"
    Traceback (most recent call last):
    File "./macro2m4.py", line 56, in <module>
      m = Macro(m4File, computeSerialNumber=True)
    File "~/src/autoconf-archive/macro.py", line 62, in __init__
      (header,body) = loadFile(filePath).split("\n\n", 1)
    File "~/src/autoconf-archive/macro.py", line 8, in loadFile
      return fd.read()
    File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3615: ordinal not in range(128)
    cfg.mk:35: recipe for target 'stage/ax_compiler_flags_cflags.m4' failed
    make: *** [stage/ax_compiler_flags_cflags.m4] Error 1

This error might only occur when using Python 3.

Since all affected characters were apostrophes in comments, I simply replaced
them with ASCII character 39.

The serial numbers of the files were incremented.