ax_boost_process: migrate compile code to process::v2
Since boost 1.88, ::process::v1 is deprecated and ::process::v2 is the
default. AX_BOOST_PROCESS macro is failing to detect the library because
of the following compile failure :

> configure:24504: checking whether the Boost::Process library is available
> configure:24530: g++ -c   -I/usr/include conftest.cpp >&5
> conftest.cpp: In function 'int main()':
> conftest.cpp:59:17: error: 'child' is not a member of 'boost::process'
>    59 | boost::process::child* child = new boost::process::child; delete child;
>       |                 ^~~~~
> conftest.cpp:59:24: error: 'child' was not declared in this scope
>    59 | boost::process::child* child = new boost::process::child; delete child;
>       |                        ^~~~~
> conftest.cpp:59:52: error: 'child' in namespace 'boost::process' does not name a type
>    59 | boost::process::child* child = new boost::process::child; delete child;
>       |                                                    ^~~~~
> conftest.cpp:59:59: error: type '<type error>' argument given to 'delete', expected pointer
>    59 | boost::process::child* child = new boost::process::child; delete child;
>       |                                                           ^~~~~~~~~~~~
> configure:24530: $? = 1

1. https://github.com/boostorg/process/commit/58586e420cf181ca865945837f6c33a46b973fd8
2. https://github.com/boostorg/process/commit/2ccd97cd48c5468b0609a488b59253efaa381711

Signed-off-by: Fabrice Delliaux <netbox253@gmail.com>