ax_pthread.m4: avoid unused-but-set-parameter warning
With gcc's warning -Wunused-but-set-parameter enabled (which is enabled
with -Wextra) and -Werror, configuring with the AX_PTHREAD macro fails
with:

    configure:6783: checking whether pthreads work with -pthread
    configure:6877: ccache gcc -o conftest -g3 -O0 -Werror -Wall -Wextra  -fmax-errors=1 -fdiagnostics-color=always -Wall -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_22 -pthread   conftest.c   >&5
    conftest.c: In function 'routine':
    conftest.c:37:51: error: parameter 'a' set but not used [-Werror=unused-but-set-parameter]
                             static void routine(void *a) { a = 0; }
                                                       ^
    cc1: all warnings being treated as errors

Change the code to make it use, not only set, the parameter.