AX_PTHREAD: fix compiler warning in AC_TRY_LINK test program
The test program generated by AX_PTHREAD's AC_TRY_LINK invocation generates a
compiler warning (on Linux, using GCC 4). When building with "-Wall -Werror" in
CFLAGS, as done during development to catch unexpected warnings, this turns
into a compiler error; hence, all of the AC_TRY_LINK invocations fail, and the
macro fails to detect any suitable compiler/linker flags for pthreads usage.

A sample from config.log showing the error follows.

  configure:16038: result: no
  configure:15936: checking whether pthreads work without any flags
  configure:16029: gcc -o conftest -O3 -g -Wall -Werror -pipe -fvisibility=hidden -Wl,-O1 -Wl,--as-needed conftest.c >&5
  cc1: warnings being treated as errors
  conftest.c: In function 'main':
  conftest.c:31: error: 'th' is used uninitialized in this function

This patch fixes the issue by placing pthread_create before pthread_join in the
test program.