AX_CXX_COMPILE_STDCXX_0X: Fix for -Werror=missing-declarations
This fixes the following error:

  conftest.cpp:49:14: error: no previous declaration for 'void
  test_template_alias_sfinae::test()' [-Werror=missing-declarations]