ax_have_epoll: avoid -Wunused-but-set-variable errors
When building with -Werror -Wunused-but-set-variable, the code snippets
in this file generate a warning, causing the test to spuriously fail.
Remove the "rc" variables, since they're not used.

Sample config.log output:

    configure:22489: checking for Linux epoll(7) interface
    configure:22515: ccache gcc -o conftest -g3 -O0 -Wall -Werror -Wextra -Wno-type-limits -Wno-missing-declarations -Wno-missing-field-initializers -Wno-si      gn-compare -Wno-implicit-fallthrough -Wno-unused-parameter -I/home/smarchi/install/include -DHAVE_LINUX_VERSION_H -L/home/smarchi/install/lib conftest.c       -lurcu-cds  >&5
    conftest.c: In function 'main':
    conftest.c:184:9: error: variable 'rc' set but not used [-Werror=unused-but-set-variable]
     int fd, rc;
             ^~
    cc1: all warnings being treated as errors